# server properties
server:
 port: 8083

# spring properties
spring:
 application:
  name: PENSIONER-DETAIL-SERVICE
 h2:
    console:
      enabled: true
 datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
    driverClassName: org.h2.Driver
 jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  
#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # add public IP link here
      defaultZone: http://localhost:8761/eureka/

# Error Messages
errorMessage: Aadhaar Number Not Found
